version: '3'
services:
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: api